front:
  build: .
  ports:
    - "80:80"
  links:
    - postgis:postgis
    - memcached:memcached
  volumes:
    - ./www:/var/www
    - ./sites:/etc/apache2/sites-enabled
    - ./logs:/var/log/supervisor

postgis:
  image: kartoza/postgis:9.4-2.1
  volumes_from:
    - data
  ports:
    - "5432:5432"

data:
  image: kartoza/postgis:9.4-2.1
  volumes:
    - /var/lib/postgresql
  command: "true"

memcached:
  image: memcached
  ports:
    - "11211:11211"